spring:
    datasource:
        name: test
        url: jdbc:mysql://119.27.188.151:3306/cake?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123454321
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        sql-script-encoding: utf-8
    thymeleaf:
      mode: HTML5
      prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:com/example/cake/dao/*.xml
  type-aliases-package: com.example.cake.entity